mixed-port: 52138
bind-address: "127.0.0.1"

proxies:
  - name: proxy1
    type: http
    server: 127.0.0.1
    port: 23569

proxy-groups:
  - name: fallback-group
    type: fallback
    proxies:
      - proxy1
      - DIRECT
    url: https://github.com/robots.txt
    interval: 300

rules:
  - MATCH,fallback-group
